# docker compose -f docker-compose-app.yml up -d

services:

  # Nginx
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/xfg-studio/nginx:latest
    container_name: nginx
    restart: always

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/html:/usr/share/nginx/html

    networks:
      - my-network


#  ai-agent-scaffold-lite:
#    image: system/ai-agent-scaffold-lite:1.0
#    container_name: ai-agent-scaffold-lite
#    restart: on-failure
#
#    ports:
#      - "8091:8091"
#
#    environment:
#      - TZ=Asia/Shanghai
#      - SERVER_PORT=8091
#
#    volumes:
#      - ./log:/data/log
#
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"
#        max-file: "3"
#
#    networks:
#      - my-network


# 使用服务器上已经创建好的 Docker 网络
networks:
  my-network:
    external: true
    name: my-network